## Pytorch

In [1]:
import torch 
import numpy as np

In [6]:
A = torch.from_numpy(np.array([[2., 3.], [1., 0.]]))
A.requires_grad = True

B = torch.from_numpy(np.array([[1., 2.], [3., 4.]]))
B.requires_grad = True

d =  torch.from_numpy(np.array([[3.], [2.]]))
d.requires_grad = True

C = torch.matmul(A, B)

E = C + d

J = torch.sum(E)

Pytorch a stocké les différentes opérations que l'on a effectué afin de réaliser le backward pass, il nous faut seulement ajouter la mention `requires_grad`

In [8]:
J.backward()

On ne peut cependant accéder aux gradients intermédiaires, seulement à ceux des feuilles:

In [9]:
A.grad

tensor([[3., 7.],
        [3., 7.]], dtype=torch.float64)

In [10]:
B.grad

tensor([[3., 3.],
        [3., 3.]], dtype=torch.float64)

In [11]:
d.grad

tensor([[2.],
        [2.]], dtype=torch.float64)